---
# tasks file for backend-deploy
- name: Copy be template
  become: true
  copy:
    src: ../roles/backend-deploy/templates/be-template.j2
    dest: /etc/nginx/sites-available/backend

- name: Link to site-enabled
  file:
    src: /etc/nginx/sites-available/backend
    dest: /etc/nginx/sites-enabled/backend
    state: link
  become: true
  notify: Restart nginx

# - name: Run PHP Artisan Serve
#   command:
#     cmd: "nohup php artisan serve --port=9000 &"
#     chdir: "/var/www/be-todo"

- name: Curl result
  uri:
    url: "http://localhost:8000"
    method: GET
    return_content: yes
  register: result

- name: Display response
  debug:
    var: result.content